### ISSUE TITLE
Revert develop branch merge to the master branch

### ISSUE THREAD

**Issue by arwhyte** [IMSGlobal/caliper-net#133]
@apn114 -- Develop branch code must not be merged to the master branch until respective spec and/or standalone profile documents are merged to the caliper-spec master branch.

Please revert.

https://github.com/IMSGlobal/caliper-net/pull/132

**Comment by apn114** [comment]
Thank you for the clarification! The merge has been reverted.

**Comment by aviade** [comment]
@apn114  - do you have an ETA for merging the develop branch? It seems like it's way behind Master and is unstable to a point where we can't work with it (some of the tests fail locally and it references a different version of caliper-common-fixtures).

**Comment by ViktorHaag** [comment]
Hey, @aviade -- the way we use the `develop` and `master` branches is a bit different than typical, due to the way that IMS works on and releases projects. Basically, `master` and `develop` are two, permanent, long-running branches -- `master` exists only for tagging and releasing "approved" releases of a specification and related work to the public; `develop` is where all the work towards such a public release gets done.

Accordingly, when we approach the time when we have candidate-final assets for the Caliper v1.2 release, we will prepare all those assets (and adjust them according to final revision needs) in their respective `develop` branches; then, when the IMS technical advisory board votes to approve the Caliper v1.2 release, the appropriate commits in the various `develop` branches will get tagged as Caliper v1.2 release candidate final, and merged up into their respective `master` branches, and then tagged as Caliper v1.2 final public release.

The master branches only exist in order to create public release bundles, and (from time to time) correct errata or defects in those public releases.
